In [1]:
# import required packages
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

import matplotlib.pyplot as plt
import numpy as np
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

import warnings
warnings.filterwarnings('ignore')

In [2]:
house = pd.read_excel("dataset.xlsx",engine='openpyxl')
house.shape

(414, 8)

In [3]:
house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 8 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   No                                      414 non-null    int64
 1   X1 transaction date                     414 non-null    float64
 2   X2 house age                            414 non-null    float64
 3   X3 distance to the nearest MRT station  414 non-null    float64
 4   X4 number of convenience stores         414 non-null    int64
 5   X5 latitude                             414 non-null    float64
 6   X6 longitude                            414 non-null    float64
 7   Y house price of unit area              414 non-null    float64
dtypes: float64(6), int64(2)
memory usage: 26.0 KB

In [4]:
house

,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,1,2012.916667,32.0,84.87882,10,24.98298,121.54024,37.9
1,2,2012.916667,19.5,306.59470,9,24.98034,121.53951,42.2
2,3,2013.583333,13.3,561.98450,5,24.98746,121.54391,47.3
3,4,2013.500000,13.3,561.98450,5,24.98746,121.54391,54.8
4,5,2012.833333,5.0,390.56840,5,24.97937,121.54245,43.1
...,...,...,...,...,...,...,...,...
409,410,2013.000000,13.7,4082.01500,0,24.94155,121.50381,15.4
410,411,2012.666667,5.6,90.45606,9,24.97433,121.54310,50.0
411,412,2013.250000,18.8,390.96960,7,24.97923,121.53986,40.6
412,413,2013.000000,8.1,104.81010,5,24.96674,121.54067,52.5
413,414,2013.500000,6.5,90.45606,9,24.97433,121.54310,63.9

In [13]:
# creating a simple OLS for investigating the relationships of age and cholesterol
# Identifying dependent and independent variables
Y = house["Y house price of unit area"]
X = house[["X1 transaction date", "X2 house age","X3 distance to the nearest MRT station","X4 number of convenience stores","X5 latitude","X6 longitude"]]

# Splitting data to train and test
X_train , X_test, Y_train, Y_test = train_test_split(X, Y, test_size= 0.1, random_state=42)

# Create linear regression object
regr = linear_model.LinearRegression()

# X_train=X_train.values.reshape(-1, 1)
# X_test=X_test.values.reshape(-1, 1)
# Train the model using the training sets
regr.fit(X_train, Y_train)

# Make predictions using the testing set
Y_pred = regr.predict(X_test)

# The coefficients
print("Coefficients: \n", regr.coef_)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(Y_test, Y_pred))
# The coefficient of determination: 1 is perfect prediction
print("Coefficient of determination R^2: %.2f" % r2_score(Y_test, Y_pred))

Coefficients:
 [ 5.38848795e+00 -2.92491285e-01 -4.86719894e-03  1.06986698e+00
  2.15671934e+02 -3.17878488e+01]
Mean squared error: 70.71
Coefficient of determination R^2: 0.64

In [14]:
# creating a simple OLS for investigating the relationships of age and cholesterol
# Identifying dependent and independent variables
Y = house["Y house price of unit area"]
X = house[["X1 transaction date", "X2 house age","X3 distance to the nearest MRT station","X4 number of convenience stores","X5 latitude","X6 longitude"]]

# Splitting data to train and test
X_train , X_test, Y_train, Y_test = train_test_split(X, Y, test_size= 0.1, random_state=42)

# Create linear regression object
regr = linear_model.Ridge(alpha=0.95)

# X_train=X_train.values.reshape(-1, 1)
# X_test=X_test.values.reshape(-1, 1)
# Train the model using the training sets
regr.fit(X_train, Y_train)

# Make predictions using the testing set
Y_pred = regr.predict(X_test)

# The coefficients
print("Coefficients: \n", regr.coef_)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(Y_test, Y_pred))
# The coefficient of determination: 1 is perfect prediction
print("Coefficient of determination R^2: %.2f" % r2_score(Y_test, Y_pred))

Coefficients:
 [ 5.63497837e+00 -2.75326550e-01 -5.58985576e-03  1.19634268e+00
  8.27606137e+00 -1.89141724e+00]
Mean squared error: 75.66
Coefficient of determination R^2: 0.61

In [15]:
# creating a simple OLS for investigating the relationships of age and cholesterol
# Identifying dependent and independent variables
Y = house["Y house price of unit area"]
X = house[["X1 transaction date", "X2 house age","X3 distance to the nearest MRT station","X4 number of convenience stores","X5 latitude","X6 longitude"]]

# Splitting data to train and test
X_train , X_test, Y_train, Y_test = train_test_split(X, Y, test_size= 0.1, random_state=42)

# Create linear regression object
regr = linear_model.Lasso(alpha=0.5)

# X_train=X_train.values.reshape(-1, 1)
# X_test=X_test.values.reshape(-1, 1)
# Train the model using the training sets
regr.fit(X_train, Y_train)

# Make predictions using the testing set
Y_pred = regr.predict(X_test)

# The coefficients
print("Coefficients: \n", regr.coef_)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(Y_test, Y_pred))
# The coefficient of determination: 1 is perfect prediction
print("Coefficient of determination R^2: %.2f" % r2_score(Y_test, Y_pred))

Coefficients:
 [ 0.         -0.26792644 -0.00561044  1.12890207  0.         -0.        ]
Mean squared error: 78.79
Coefficient of determination R^2: 0.60

In [16]:
# creating a simple OLS for investigating the relationships of age and cholesterol
# Identifying dependent and independent variables
Y = house["Y house price of unit area"]
X = house[["X1 transaction date", "X2 house age","X3 distance to the nearest MRT station","X4 number of convenience stores","X5 latitude","X6 longitude"]]

# Splitting data to train and test
X_train , X_test, Y_train, Y_test = train_test_split(X, Y, test_size= 0.1, random_state=42)

# Create linear regression object
regr = linear_model.ElasticNet(alpha=0.5, l1_ratio=0.5)

# X_train=X_train.values.reshape(-1, 1)
# X_test=X_test.values.reshape(-1, 1)
# Train the model using the training sets
regr.fit(X_train, Y_train)

# Make predictions using the testing set
Y_pred = regr.predict(X_test)

# The coefficients
print("Coefficients: \n", regr.coef_)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(Y_test, Y_pred))
# The coefficient of determination: 1 is perfect prediction
print("Coefficient of determination R^2: %.2f" % r2_score(Y_test, Y_pred))

Coefficients:
 [ 0.64769267 -0.26940441 -0.00563345  1.12145248  0.         -0.        ]
Mean squared error: 78.39
Coefficient of determination R^2: 0.60